spring:
  application:
    name: spring-boot-jasypt


jasypt:
  encryptor:
    password: moonzhou

user:
  name: aaa
  age: 18
  desc: ENC(aJQZQo9C0/a/R9zKkiFjGRk48p3HpqvVCnF0Sbcaysm4SUzh02jDF9zMqbS0ZRP1)