spring:
  profiles:
    active: prd
    #active: @select.config@
    include:
      - security
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8080
  shutdown: graceful

# 端点配置，建议使用白名单方式，不要用黑名单方式，且慎重打开
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans

system-info:
  code: 001
  name: spring-boot-profile


# 因为多配置文件问题，为了更好的复用，直接将此处的配置注释掉，如果运行示例时，可以自行放开注释
#---
#spring:
#  profiles: dev
#server:
#  port: 8081
#---
#spring:
#  profiles: pre
#server:
#  port: 8082
#---
#spring:
#  profiles: prd
#server:
#  port: 8083