# application.yml
spring:
  datasource:
    # mysql5:com.mysql.jdbc.Driver, mysql8 below
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/moon_mybatis_plus_schema.sql
    data: classpath:db/moon_mybatis_plus_data.sql
    url: jdbc:mysql://localhost:3306/moon_mybatis_plus?serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis-plus:
  mapper-locations: classpath*:/sql/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
