# application.yml
spring:
  datasource:
    # mysql5:com.mysql.jdbc.Driver, mysql8 below
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/moon_mybatis_plus_schema.sql
    data: classpath:db/moon_mybatis_plus_data.sql
    url: jdbc:mysql://localhost:3306/moon_mybatis_plus?serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis-plus:
  mapper-locations: classpath*:/sql/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

moon:
  mybatis:
    column-encrypt:
      aes-secret-key: 1234567890abcdef