spring:
  application:
    name: spring-boot-xss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/moon?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    # 配置初始化大小（默认0）、最小、最大（默认8）
    initial-size: 1
    min-idle: 1
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大。 默认为false
    pool-prepared-statements: true
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-open-prepared-statements: 20
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小和最大生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    max-evictable-idle-time-millis: 900000

    # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
    # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
    validation-query: SELECT 1
    # 申请连接时执行validationQuery检测连接是否有效 默认为true
    test-on-borrow: true
    # 归还连接时执行validationQuery检测连接是否有效 默认为false
    test-on-return: false
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true

mybatis:
  # 自动配置别名，在Mybatis的Mapper文件里面就可以直接写对应的类名而不用写全路径名了
  type-aliases-package: org.moonzhou.xss.dmo
  # xml配置方式，xml文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080